#!/usr/bin/env ruby

definitely_lost_pattern = 'definitely.+lost:.+(\d+).+bytes.+in.+(\d+).+blocks'

def has_leak(leak_data)
  0 < leak_data[2].to_i
end

had_leak = false
file_cache = []

File.open( ARGV[0], "r" ) do | file |
  file.each_line do | line |
    file_cache << line
    leak_data = /#{definitely_lost_pattern}/.match( line ) || next
    had_leak||=has_leak( leak_data )
  end
end

if (had_leak)
  puts file_cache
  raise( "memory leak detected" );
end

